CREATE TABLE "pages" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "url" TEXT NOT NULL,
  "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "links" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "from_page_id" INTEGER NOT NULL,
  "to_page_id" INTEGER NOT NULL,
  "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);